name: Continous Delivery Workflow
on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Simulando CD
        uses: actions/upload-artifact@v7
        with:
          name: projetozipado.zip
          path: |
            - main.py
            - README.md