name: Continous Integration Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Pylint
        run: pip install pylint fastapi

      - name: Run Pylint
        run: pylint src/main.py --disable=C0114,C0116

  discord:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Run Discord Webhook
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ needs.build.result }}
          title: "Resultado do Workflow"
          description: "O job de build terminou com status: ${{ needs.build.result }}"
          color: 0x0000ff
  testes:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi pytest pytest-cov
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pytest test/test.py --cov=main --cov-report=xml
